GET http://localhost:9090/check
Content-Type: application/json

{
  "name" : "egorsni",
  "password": "qwerty",
  "balance" : 0
}
###
GET http://localhost:9090/list
Content-Type: application/json
###
GET http://localhost:9090/balance/egorsni
Content-Type: application/json
###
POST http://localhost:9090/balance/egorsni
Content-Type: application/json

1000.0
###
GET http://localhost:9090/list/egorsni
Content-Type: application/json
###
POST http://localhost:9090/case/egorsni
Content-Type: application/json

{
  "symbol" : "AAPL",
  "count" : 0
}
###
POST http://localhost:9090/case/egorsni
Content-Type: application/json

{
  "symbol" : "TSLA",
  "price" : 100.0,
  "count" : 0
}
###
DELETE http://localhost:9090/case/egorsni
Content-Type: application/json

{
  "symbol" : "TSLA",
  "count" : 0
}
###
DELETE http://localhost:9090/case/egorsni
Content-Type: application/json

{
  "symbol" : "AAPL",
  "count" : 0
}
